### ISSUE TITLE
看起來是否因為改版問題而不能使用了？

### ISSUE THREAD

**Issue by Yuehua-Liu** [xxxspy/baiduIndexDownloader#3]
我按照安裝流程進行操作
在百度指數頁面可以看到「下載JSON」、「下載CSV」文字
但是點下去後沒有反應

我檢查了一下插件區，看到如下的錯誤說明
不知道是不是因為改版或者其他原因導致的
再麻煩大大協助看一下是甚麼原因，謝謝 ~

![image](https://user-images.githubusercontent.com/13415294/172578608-5d7bc94c-7bc0-4b9b-add8-c1cf36a2d340.png)

![image](https://user-images.githubusercontent.com/13415294/172578859-863b46c2-fc2b-4768-8efe-12db42daee88.png)

**Comment by Yuehua-Liu** [comment]
我把這段 Result 結果試著 Print 出來後
發現得到的東西已經被屏蔽
看來是有某些行為已經被偵測到是機器人使用行為了

![image](https://user-images.githubusercontent.com/13415294/172755336-54e704c9-07c8-46a2-be27-865b395f2ada.png)

![image](https://user-images.githubusercontent.com/13415294/172755508-d68bbad1-4979-42f9-ac68-2eb05867346a.png)

**Comment by xxxspy** [comment]
该问题已经解决,新版本已经可以下载了
